### DISCUSSION TITLE
Question about FHIR search parameters

### DISCUSSION THREAD

**Discussion by m-onyshchuk** [LinuxForHealth/connect#349] [Q&A] [answered]
Hello everybody!
I am trying FHIR Server and have some questions about search parameters. 
I can`t to attach favorite-color parameter from example here: https://linuxforhealth.github.io/FHIR/guides/FHIRSearchConfiguration#11-tenant-specific-parameters
Files from my test are below

docker-compose.yml:
```
version: '3.7'

services:
  fhir-server:
    image: ibmcom/ibm-fhir-server
    container_name: fhir-server
    environment:
      - BOOTSTRAP_DB=true
    ports:
      - 9443:9443
    volumes:
      - "./favorite-color.json:/opt/ol/wlp/usr/servers/defaultServer/config/favorite-color/extension-search-parameters.json"
```

./favorite-color.json:
```
{
  "fullUrl": "http://ibm.com/fhir/SearchParameter/Patient-favorite-color",
  "resource": {
    "resourceType": "SearchParameter",
    "id": "Patient-favorite-color",
    "url": "http://ibm.com/fhir/SearchParameter/Patient-favorite-color",
    "version": "4.0.0",
    "name": "favorite-color",
    "status": "draft",
    "experimental": false,
    "date": "2018-12-27T22:37:54+11:00",
    "publisher": "IBM FHIR Server Test",
    "contact": [{
      "telecom": [{
        "system": "url",
        "value": "http://ibm.com/fhir"
      }]
    },
      {
        "telecom": [{
          "system": "url",
          "value": "http://ibm.com/fhir"
        }]
      }],
    "description": "the patient's favorite color",
    "code": "favorite-color",
    "base": ["Patient"],
    "type": "string",
    "xpathUsage": "normal",
    "xpath": "f:Patient/f:extension[@url='http://ibm.com/fhir/extension/Patient/favorite-color']/f:valueString",
    "expression": "Patient.extension.where(url='http://ibm.com/fhir/extension/Patient/favorite-color').value",
    "multipleOr": true,
    "multipleAnd": true,
    "modifier": []
  }
}
```

Аfter composition's start I did request: 
```
GET https://localhost:9443/fhir-server/api/v4/Patient?favorite-color=pink
```

Responce:
```
{
  "resourceType": "OperationOutcome",
  "id": "c0-a8-20-3-93281f96-bea0-41e0-84a8-4c365d8d4bb4",
  "issue": [
    {
      "severity": "fatal",
      "code": "invalid",
      "details": {
        "text": "Search parameter 'favorite-color' for resource type 'Patient' was not found."
      }
    }
  ]
}
```
Tell me please where is the mistake in my example?
