### ISSUE TITLE
Support Trace Logging Via a Method

### ISSUE THREAD

**Issue by dixonwhitmire** [LinuxForHealth/connect#155]
Let's see if we can take our current trace logging facility and support it as a logger instance method.

**Comment by dixonwhitmire** [comment]
I have trace logging running within a local feature branch. Trace logging is configured using a bootstrapping method integrated within server handlers
```python
def add_trace_logging():
    """
    Adds trace level logging support to logging and the root logging class
    """

    def trace(self, message, *args, **kwargs):
        """
        Generates a TRACE log record
        """
        self.log(5, message, *args, **kwargs)

    logging.addLevelName(5, "TRACE")
    logging.getLoggerClass().trace = trace
```
Logging config
```yaml
version: 1
disable_existing_loggers: false
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: TRACE
    formatter: simple
    stream: ext://sys.stdout
root:
  level: WARN
  handlers: [console]
loggers:
  connect:
    level: TRACE
  uvicorn:
    level: INFO
```
I will also test with the handler set to DEBUG to verify that we aren't emitting log events.
